### ISSUE TITLE
You are missing `%o` and `%O` format specifiers

### ISSUE THREAD

**Issue by niftylettuce** [Xotic750/util-format-x#1]
https://github.com/nodejs/node/blob/master/doc/api/util.md#utilformatformat-args

https://www.npmjs.com/package/format-specifiers

**Comment by Xotic750** [comment]
Yes, this was based on the spec for over 2 years ago and I haven't had time to update it or many of the dependencies.

**Comment by Xotic750** [comment]
All dependencies have now been updated, and I hope to bring the project up to current spec soon.

**Comment by Xotic750** [comment]
@niftylettuce Updated and it is now supported.
