### ISSUE TITLE
package.json "main" reference is inaccurate, there is no build for Node

### ISSUE THREAD

**Issue by niftylettuce** [Xotic750/util-format-x#2]
The package.json file here https://github.com/Xotic750/util-format-x/blob/master/package.json#L24 contains "main" equal to a webpack build.  This "main" should instead be changed to "browser", and a new "main" should get added that is a Node.js compiled version (e.g. it has import vs require).

**Comment by niftylettuce** [comment]
Reason being is because if you `require('util-format-x')` right now.. it requires a file that is over 10K lines of code.

**Comment by Xotic750** [comment]
There is the ESM build "module" that gets used, at least when I am using webpack to include this module, though I am using "import x from 'x'" in my code. I have toyed with creating a CJS build and moving main to browser but haven't had time to convert my 200 projects yet. I don't think that it will make any builds smaller though, everything that this module requires will still be required and added to you build so the result will be the same.
